const toast=document.querySelector('.toast');
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
document.querySelectorAll('.role-tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.role-tab').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.portal').forEach(v=>v.classList.toggle('active',v.id===`${button.dataset.view}View`));window.scrollTo({top:0,behavior:'smooth'})}));
const students={aanya:{name:'Aanya Patel',initials:'AP',grade:'Grade 6',tutor:'Jordan Lee',attendance:'92%',remaining:'5',days:['Sep 22','Sep 24','Sep 29','Oct 1','Oct 5'],topics:'Equivalent ratios, unit rates, percent increase, and argument structure.',notes:'Strong verbal reasoning. Continue written explanations and complete pages 12–14.',files:['Ratios-practice.pdf','Argument-structure-guide.pdf']},jackson:{name:'Jackson Miller',initials:'JM',grade:'Grade 9',tutor:'Jordan Lee',attendance:'96%',remaining:'4',days:['Sep 23','Sep 26','Sep 30','Oct 3','Oct 6'],topics:'Linear equations, slope-intercept form, and systems of equations.',notes:'Accurate graphing. Practice translating word problems into equations.',files:['Linear-equations-set.pdf','Systems-review.pdf']},ethan:{name:'Ethan Nguyen',initials:'EN',grade:'Grade 10',tutor:'Daniel Kim',attendance:'98%',remaining:'7',days:['Sep 21','Sep 25','Sep 28','Oct 2','Oct 5'],topics:'SAT reading analysis, transitions, advanced algebra, and pacing.',notes:'Excellent accuracy. Focus on completing reading modules within time.',files:['SAT-reading-strategy.pdf','Practice-test-2.pdf']}};
const studentDialog=document.querySelector('#studentDialog');
document.querySelectorAll('.student-row').forEach(row=>row.addEventListener('click',()=>{const s=students[row.dataset.student];document.querySelector('#studentDetail').innerHTML=`<div class="detail-head"><span class="avatar">${s.initials}</span><div><p class="eyebrow">STUDENT RECORD</p><h2>${s.name}</h2><p>${s.grade} · ${s.tutor}</p></div></div><div class="detail-grid"><div><small>Attendance</small><strong>${s.attendance}</strong></div><div><small>Classes remaining</small><strong>${s.remaining}</strong></div><div><small>Next session</small><strong>Oct 8 · 5:00 PM</strong></div></div><div class="detail-section"><h3>Days attended</h3><div class="chips">${s.days.map(d=>`<span>✓ ${d}</span>`).join('')}</div></div><div class="detail-section"><h3>Topics covered</h3><p>${s.topics}</p></div><div class="detail-section"><h3>Notes</h3><p>${s.notes}</p></div><div class="detail-section"><h3>PDFs and assignments</h3>${s.files.map(f=>`<div class="payment-row"><span>${f}</span><span></span><button class="text-btn">Open</button></div>`).join('')}<label class="upload large"><input type="file" multiple><span>＋ Upload PDF or assignment</span></label></div>`;studentDialog.showModal()}));
document.querySelectorAll('.search').forEach(input=>input.addEventListener('input',()=>{const list=input.closest('.card').querySelectorAll('.student-row');list.forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(input.value.toLowerCase()))}));
const addDialog=document.querySelector('#addDialog');document.querySelectorAll('.add-student').forEach(button=>button.addEventListener('click',()=>addDialog.showModal()));document.querySelectorAll('dialog .close').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
document.querySelector('#sessionForm').addEventListener('submit',e=>{e.preventDefault();notify('Session saved and parent dashboard updated');e.target.reset()});document.querySelector('#addForm').addEventListener('submit',e=>{e.preventDefault();addDialog.close();notify('Student added successfully');e.target.reset()});document.querySelector('.copy-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('https://daksh-j-prajapati.github.io/roave-education/')}catch{}notify('Referral link copied')});document.querySelectorAll('input[type=file]').forEach(input=>input.addEventListener('change',()=>input.files.length&&notify(`${input.files.length} file uploaded`)));
